<a href="https://cognitiveclass.ai"><img src = "https://ibm.box.com/shared/static/ugcqz6ohbvff804xp84y4kqnvvk3bq1g.png" width = 300, align = "center"></a>

<h1 align=center><font size = 5>Lab: Working with a real world data-set using SQL and Python</font></h1>

# Introduction

This notebook shows how to work with a real world dataset using SQL and Python. In this lab you will:
1. Understand the dataset for Chicago Public School level performance 
1. Store the dataset in an Db2 database on IBM Cloud instance
1. Retrieve metadata about tables and columns and query data from mixed case columns
1. Solve example problems to practice your SQL skills including using built-in database functions

## Chicago Public Schools - Progress Report Cards (2011-2012) 

The city of Chicago released a dataset showing all school level performance data used to create School Report Cards for the 2011-2012 school year. The dataset is available from the Chicago Data Portal: https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t

This dataset includes a large number of metrics. Start by familiarizing yourself with the types of metrics in the database: https://data.cityofchicago.org/api/assets/AAD41A13-BE8A-4E67-B1F5-86E711E09D5F?download=true

__NOTE__: Do not download the dataset directly from City of Chicago portal. Instead download a more database friendly version from the link below.
Now download a static copy of this database and review some of its contents:
https://ibm.box.com/shared/static/f9gjvj1gjmxxzycdhplzt01qtz0s7ew7.csv

### Store the dataset in a Table
In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. To analyze the data using SQL, it first needs to be stored in the database.

While it is easier to read the dataset into a Pandas dataframe and then PERSIST it into the database as we saw in the previous lab, it results in mapping to default datatypes which may not be optimal for SQL querying. For example a long textual field may map to a CLOB instead of a VARCHAR. 

Therefore, __it is highly recommended to manually load the table using the database console LOAD tool, as indicated in Week 2 Lab 1 Part II__. The only difference with that lab is that in Step 5 of the instructions you will need to click on create "(+) New Table" and specify the name of the table you want to create and then click "Next". 

##### Now open the Db2 console, open the LOAD tool, Select / Drag the .CSV file for the CHICAGO PUBLIC SCHOOLS dataset and load the dataset into a new table called __SCHOOLS__.

<a href="https://cognitiveclass.ai"><img src = "https://ibm.box.com/shared/static/uc4xjh1uxcc78ks1i18v668simioz4es.jpg"></a>

### Connect to the database
Let us now load the ipython-sql  extension and establish a connection with the database

In [2]:
%load_ext sql

In [3]:
# Enter the connection string for your Db2 on Cloud database instance below
# %sql ibm_db_sa://my-username:my-password@my-hostname:my-port/my-db-name
%sql ibm_db_sa://sml38235:wf81pz37trb%5Eqj2w@dashdb-txn-sbox-yp-dal09-14.services.dal.bluemix.net:50000/BLUDB;

'Connected: sml38235@BLUDB;'

### Query the database system catalog to retrieve table metadata

##### You can verify that the table creation was successful by retrieving the list of all tables in your schema and checking whether the SCHOOLS table was created

In [13]:
# type in your query to retrieve list of all tables in the database for your db2 schema (username)
%sql select TABSCHEMA, TABNAME, CREATE_TIME FROM syscat.tables where TABSCHEMA='sml38235'
#%sql select * from SYSCAT.TABLES where TABNAME = 'SCHOOLS'

 * ibm_db_sa://sml38235:***@dashdb-txn-sbox-yp-dal09-14.services.dal.bluemix.net:50000/BLUDB;
Done.

[]

Double-click __here__ for a hint

<!--
In Db2 the system catalog table called SYSCAT.TABLES contains the table metadata
-->

Double-click __here__ for the solution.

<!-- Solution:

%sql select TABSCHEMA, TABNAME, CREATE_TIME from SYSCAT.TABLES where TABSCHEMA='YOUR-DB2-USERNAME'

or, you can retrieve list of all tables where the schema name is not one of the system created ones:

%sql select TABSCHEMA, TABNAME, CREATE_TIME from SYSCAT.TABLES \
      where TABSCHEMA not in ('SYSIBM', 'SYSCAT', 'SYSSTAT', 'SYSIBMADM', 'SYSTOOLS', 'SYSPUBLIC')
      
or, just query for a specifc table that you want to verify exists in the database
%sql select * from SYSCAT.TABLES where TABNAME = 'SCHOOLS'

-->

### Query the database system catalog to retrieve column metadata

##### The SCHOOLS table contains a large number of columns. How many columns does this table have?

In [15]:
# type in your query to retrieve the number of columns in the SCHOOLS table
%sql select COUNT(*) FROM SYSCAT.COLUMNS WHERE TABNAME='SCHOOLS'

 * ibm_db_sa://sml38235:***@dashdb-txn-sbox-yp-dal09-14.services.dal.bluemix.net:50000/BLUDB;
Done.

[(Decimal('78'),)]

Double-click __here__ for a hint

<!--
In Db2 the system catalog table called SYSCAT.COLUMNS contains the column metadata
-->

Double-click __here__ for the solution.

<!-- Solution:

%sql select count(*) from SYSCAT.COLUMNS where TABNAME = 'SCHOOLS'

-->

Now retrieve the the list of columns in SCHOOLS table and their column type (datatype) and length.

In [17]:
# type in your query to retrieve all column names in the SCHOOLS table along with their datatypes and length
%sql select DISTINCT(NAME), COLTYPE, LENGTH FROM SYSIBM.SYSCOLUMNS WHERE TBNAME='SCHOOLS'

 * ibm_db_sa://sml38235:***@dashdb-txn-sbox-yp-dal09-14.services.dal.bluemix.net:50000/BLUDB;
Done.

[('10th Grade PLAN (2009)', 'VARCHAR ', 4),
 ('10th Grade PLAN (2010)', 'VARCHAR ', 4),
 ('11th Grade Average ACT (2011)', 'VARCHAR ', 4),
 ('9th Grade EXPLORE (2009)', 'VARCHAR ', 4),
 ('9th Grade EXPLORE (2010)', 'VARCHAR ', 4),
 ('AVERAGE_STUDENT_ATTENDANCE', 'VARCHAR ', 6),
 ('Adequate_Yearly_Progress_Made_', 'VARCHAR ', 3),
 ('Average_Teacher_Attendance', 'VARCHAR ', 6),
 ('COLLEGE_ENROLLMENT', 'SMALLINT', 2),
 ('COMMUNITY_AREA_NAME', 'VARCHAR ', 22),
 ('COMMUNITY_AREA_NUMBER', 'SMALLINT', 2),
 ('CPS_Performance_Policy_Level', 'VARCHAR ', 15),
 ('CPS_Performance_Policy_Status', 'VARCHAR ', 16),
 ('City', 'VARCHAR ', 7),
 ('Collaborative_Name', 'VARCHAR ', 34),
 ('College_Eligibility__', 'VARCHAR ', 4),
 ('College_Enrollment_Rate__', 'VARCHAR ', 4),
 ('Elementary, Middle, or High School', 'VARCHAR ', 2),
 ('Environment_Icon', 'VARCHAR ', 11),
 ('Environment_Score', 'SMALLINT', 2),
 ('Family_Involvement_Icon', 'VARCHAR ', 11),
 ('Family_Involvement_Score', 'VARCHAR ', 3),
 ('Freshman_on_Track_Rate__', 'VARCHAR ', 4),
 ('General_Services_Route', 'SMALLINT', 2),
 ('Gr3_5_Grade_Level_Math__', 'VARCHAR ', 4),
 ('Gr3_5_Grade_Level_Read__', 'VARCHAR ', 4),
 ('Gr3_5_Keep_Pace_Math__', 'VARCHAR ', 4),
 ('Gr3_5_Keep_Pace_Read__', 'VARCHAR ', 4),
 ('Gr6_8_Grade_Level_Math__', 'VARCHAR ', 4),
 ('Gr6_8_Grade_Level_Read__', 'VARCHAR ', 4),
 ('Gr6_8_Keep_Pace_Math_', 'VARCHAR ', 4),
 ('Gr6_8_Keep_Pace_Read__', 'VARCHAR ', 4),
 ('Gr_8_Explore_Math__', 'VARCHAR ', 4),
 ('Gr_8_Explore_Read__', 'VARCHAR ', 4),
 ('Graduation_Rate__', 'VARCHAR ', 4),
 ('HEALTHY_SCHOOL_CERTIFIED', 'VARCHAR ', 3),
 ('ISAT_Exceeding_Math__', 'DECIMAL ', 4),
 ('ISAT_Exceeding_Reading__', 'DECIMAL ', 4),
 ('ISAT_Value_Add_Color_Math', 'VARCHAR ', 6),
 ('ISAT_Value_Add_Color_Read', 'VARCHAR ', 6),
 ('ISAT_Value_Add_Math', 'DECIMAL ', 3),
 ('ISAT_Value_Add_Read', 'DECIMAL ', 3),
 ('Individualized_Education_Program_Compliance_Rate', 'VARCHAR ', 7),
 ('Instruction_Icon', 'VARCHAR ', 11),
 ('Instruction_Score', 'SMALLINT', 2),
 ('Latitude', 'DECIMAL ', 18),
 ('Leaders_Icon', 'VARCHAR ', 11),
 ('Leaders_Score', 'VARCHAR ', 3),
 ('Link', 'VARCHAR ', 78),
 ('Location', 'VARCHAR ', 27),
 ('Longitude', 'DECIMAL ', 18),
 ('NAME_OF_SCHOOL', 'VARCHAR ', 65),
 ('Net_Change_EXPLORE_and_PLAN', 'VARCHAR ', 3),
 ('Net_Change_PLAN_and_ACT', 'VARCHAR ', 3),
 ('Network_Manager', 'VARCHAR ', 40),
 ('Parent_Engagement_Icon', 'VARCHAR ', 7),
 ('Parent_Engagement_Score', 'VARCHAR ', 3),
 ('Parent_Environment_Icon', 'VARCHAR ', 7),
 ('Parent_Environment_Score', 'VARCHAR ', 3),
 ('Phone_Number', 'VARCHAR ', 14),
 ('Pk_2_Literacy__', 'VARCHAR ', 4),
 ('Pk_2_Math__', 'VARCHAR ', 4),
 ('Police_District', 'SMALLINT', 2),
 ('Rate_of_Misconducts__per_100_students_', 'DECIMAL ', 5),
 ('SAFETY_SCORE', 'SMALLINT', 2),
 ('Safety_Icon', 'VARCHAR ', 11),
 ('School_ID', 'INTEGER ', 4),
 ('State', 'VARCHAR ', 2),
 ('Street_Address', 'VARCHAR ', 30),
 ('Students_Passing__Algebra__', 'VARCHAR ', 4),
 ('Students_Taking__Algebra__', 'VARCHAR ', 4),
 ('Teachers_Icon', 'VARCHAR ', 11),
 ('Teachers_Score', 'VARCHAR ', 3),
 ('Track_Schedule', 'VARCHAR ', 12),
 ('Ward', 'SMALLINT', 2),
 ('X_COORDINATE', 'DECIMAL ', 13),
 ('Y_COORDINATE', 'DECIMAL ', 13),
 ('ZIP_Code', 'INTEGER ', 4)]

Double-click __here__ for the solution.

<!-- Solution:

%sql select COLNAME, TYPENAME, LENGTH from SYSCAT.COLUMNS where TABNAME = 'SCHOOLS'

or

%sql select distinct(NAME), COLTYPE, LENGTH from SYSIBM.SYSCOLUMNS where TBNAME = 'SCHOOLS'

-->

### Questions
1. Is the column name for the "SCHOOL ID" attribute in upper or mixed case?
1. What is the name of "Community Area Name" column in your table? Does it have spaces?
1. Are there any columns in whose names the spaces and paranthesis (round brackets) have been replaced by the underscore character "_"?

## Problems

### Problem 1

##### How many Elementary Schools are in the dataset?

In [9]:
#%sql select count(*) from SCHOOLS where "Elementary, Middle, or High School" = 'ES'
%sql select name_of_school from SCHOOLS where "Elementary, Middle, or High School" = 'ES'

 * ibm_db_sa://sml38235:***@dashdb-txn-sbox-yp-dal09-14.services.dal.bluemix.net:50000/BLUDB;
Done.

[('Abraham Lincoln Elementary School',),
 ('Adam Clayton Powell Paideia Community Academy Elementary School',),
 ('Adlai E Stevenson Elementary School',),
 ('Agustin Lara Elementary Academy',),
 ('Albert R Sabin Elementary Magnet School',),
 ('Alessandro Volta Elementary School',),
 ('Alexander Graham Bell Elementary School',),
 ('Alexander Graham Elementary School',),
 ('Alexander Hamilton Elementary School',),
 ('Alexander von Humboldt Elementary School',),
 ('Alex Haley Elementary Academy',),
 ('Alfred David Kohn Elementary School',),
 ('Alfred Nobel Elementary School',),
 ('Alice L Barnard Computer Math & Science Center Elementary School',),
 ('Ambrose Plamondon Elementary School',),
 ('Amelia Earhart Options for Knowledge Elementary School',),
 ('Amos Alonzo Stagg Elementary School',),
 ('Ana Roque de Duprey Elementary School',),
 ('Andrew Carnegie Elementary School',),
 ('Andrew Jackson Elementary Language Academy',),
 ('Anna R. Langford Community Academy',),
 ('Annie Keller Elementary Gifted Magnet School',),
 ('A.N. Pritzker School',),
 ('Anthony Overton Elementary School',),
 ('Ariel Elementary Community Academy',),
 ('Arna Wendell Bontemps Elementary School',),
 ('Arnold Mireles Elementary Academy',),
 ('Arthur A Libby Elementary School',),
 ('Arthur Dixon Elementary School',),
 ('Arthur E Canty Elementary School',),
 ('Arthur R Ashe Elementary School',),
 ('Asa Philip Randolph Elementary School',),
 ('Ashburn Community Elementary School',),
 ('Augustus H Burley Elementary School',),
 ('Austin O Sexton Elementary School',),
 ('Avalon Park Elementary School',),
 ('Barbara Vick Early Childhood & Family Center',),
 ('Belmont-Cragin Elementary School',),
 ('Benjamin Banneker Elementary School',),
 ('Benjamin E Mays Elementary Academy',),
 ('Bernhard Moos Elementary School',),
 ('Betsy Ross Elementary School',),
 ('Beulah Shoesmith Elementary School',),
 ('Blair Early Childhood Center',),
 ('Bret Harte Elementary School',),
 ('Brian Piccolo Elementary Specialty School',),
 ('Brighton Park Elementary School',),
 ('Burnham Elementary Inclusive Academy',),
 ('Burnside Elementary Scholastic Academy',),
 ('Calmeca Academy of Fine Arts and Dual Language',),
 ('Carl von Linne Elementary School',),
 ('Carrie Jacobs Bond Elementary School',),
 ('Carroll-Rosenwald Specialty Elementary School',),
 ('Carter G Woodson South Elementary School',),
 ('Cesar E Chavez Multicultural Academic Center Elementary School',),
 ('Charles Evans Hughes Elementary School',),
 ('Charles Gates Dawes Elementary School',),
 ('Charles G Hammond Elementary School',),
 ('Charles H Wacker Elementary School',),
 ('Charles Kozminski Elementary Community Academy',),
 ('Charles N Holden Elementary School',),
 ('Charles P Caldwell Academy of Math & Science Elementary School',),
 ('Charles R Darwin Elementary School',),
 ('Charles R Henderson Elementary School',),
 ('Charles S Brownell Elementary School',),
 ('Charles S Deneen Elementary School',),
 ('Charles Sumner  Math & Science Community Acad Elementary School',),
 ('Charles W Earle Elementary School',),
 ('Chicago Academy Elementary School',),
 ('Christian Ebinger Elementary School',),
 ('Christopher Columbus Elementary School',),
 ('Clara Barton Elementary School',),
 ('Claremont Academy Elementary School',),
 ('Columbia Explorers Elementary Academy',),
 ('Countee Cullen Elementary School',),
 ('Crispus Attucks Elementary School',),
 ('Crown Community Academy of Fine Arts Center Elementary School',),
 ('Cyrus H McCormick Elementary School',),
 ('Daniel Boone Elementary School',),
 ('Daniel C Beard Elementary School',),
 ('Daniel J Corkery Elementary School',),
 ('Daniel R Cameron Elementary School',),
 ('Daniel S Wentworth Elementary School',),
 ('Daniel Webster Elementary School',),
 ('Dewey Elementary Academy of Fine Arts',),
 ('DeWitt Clinton Elementary School',),
 ('Disney II Magnet School',),
 ('Donald Morrill Math & Science Elementary School',),
 ('Douglas Taylor Elementary School',),
 ('Dr Jorge Prieto Math and Science',),
 ('Dumas Technology Academy',),
 ('Dunne Technology Academy',),
 ('Durkin Park Elementary School',),
 ('Dvorak Technology Academy',),
 ('Edgar Allan Poe Elementary Classical School',),
 ('Edgebrook Elementary School',),
 ('Edison Park Elementary School',),
 ('Edmond Burke Elementary School',),
 ('Edward A Bouchet Math & Science Academy Elementary School',),
 ('Edward Beasley Elementary Magnet Academic Center',),
 ('Edward C Delano Elementary School',),
 ('Edward Coles Elementary Language Academy',),
 ('Edward Everett Elementary School',),
 ('Edward Jenner Elementary Academy of the Arts',),
 ('Edward K Ellington Elementary School',),
 ('Edward N Hurley Elementary School',),
 ('Edward White Elementary Career Academy',),
 ('Elaine O Goodlow Elementary Magnet School',),
 ('Elihu Yale Elementary School',),
 ('Eli Whitney Elementary School',),
 ('Elizabeth H Sutherland Elementary School',),
 ('Elizabeth Peabody Elementary School',),
 ('Eliza Chappell Elementary School',),
 ('Ella Flagg Young Elementary School',),
 ('Ellen Mitchell Elementary School',),
 ('Emiliano Zapata Elementary Academy',),
 ('Emmett Louis Till Math and Science Academy',),
 ('Enrico Fermi Elementary School',),
 ('Enrico Tonti Elementary School',),
 ('Ernst Prussing Elementary School',),
 ('Esmond Elementary School',),
 ('Eugene Field Elementary School',),
 ('Everett McKinley Dirksen Elementary School',),
 ('Fairfield Elementary Academy',),
 ('Federico Garcia Lorca Elementary School',),
 ('Wilma Rudolph Elementary Learning Center',),
 ('Ferdinand Peck Elementary School',),
 ('Fernwood Elementary School',),
 ('Florence B Price Elementary School',),
 ('Florence Nightingale Elementary School',),
 ('Fort Dearborn Elementary School',),
 ('Foster Park Elementary School',),
 ('Francis M McKay Elementary School',),
 ('Francis Parkman Elementary School',),
 ('Francis Scott Key Elementary School',),
 ('Francis W Parker Elementary Community Academy',),
 ('Frank I Bennett Elementary School',),
 ('Frank L Gillespie Elementary School',),
 ('Franklin Elementary Fine Arts Center',),
 ('Frank W Gunsaulus Elementary Scholastic Academy',),
 ('Frank W Reilly Elementary School',),
 ('Franz Peter Schubert Elementary School',),
 ('Frazier Prospective IB Magnet Elementary School',),
 ('Frederic Chopin Elementary School',),
 ('Frederick Funston Elementary School',),
 ('Frederick Stock Elementary School',),
 ('Friedrich Ludwig Jahn Elementary School',),
 ('Galileo Math & Science Scholastic Academy Elementary School',),
 ('Garrett A Morgan Elementary School',),
 ('Genevieve Melody Elementary School',),
 ('George Armstrong International Studies Elementary School',),
 ('George B McClellan Elementary School',),
 ('George B Swift Elementary Specialty School',),
 ('George F Cassell Elementary School',),
 ('George Leland Elementary School',),
 ('George Manierre Elementary School',),
 ('George M Pullman Elementary School',),
 ('George Rogers Clark Elementary School',),
 ('George Washington Carver Primary School',),
 ('George Washington Elementary School',),
 ('George W Curtis Elementary School',),
 ('George W Tilton Elementary School',),
 ('Gerald Delgado Kanoon Elementary Magnet School',),
 ('Graeme Stewart Elementary School',),
 ('Granville T Woods Math & Science Academy Elementary School',),
 ('Grover Cleveland Elementary School',),
 ('Guglielmo Marconi Elementary Community Academy',),
 ('Hannah G Solomon Elementary School',),
 ('Hanson Park Elementary School',),
 ('Harold Washington Elementary School',),
 ('Harriet Beecher Stowe Elementary School',),
 ('Harriet E Sayre Elementary Language Academy',),
 ('Hawthorne Elementary Scholastic Academy',),
 ('Helen M Hefferan Elementary School',),
 ('Helen Peirce International Studies Elementary School',),
 ('Helge A Haugan Elementary School',),
 ('Henry Clay Elementary School',),
 ('Henry D Lloyd Elementary School',),
 ('Henry H Nash Elementary School',),
 ('Henry O Tanner Elementary School',),
 ('Henry R Clissold Elementary School',),
 ('Hiram H Belding Elementary School',),
 ('Horace Greeley Elementary School',),
 ('Horace Mann Elementary School',),
 ('Horatio May Elementary Community Academy',),
 ('Ida B Wells Preparatory Elementary Academy',),
 ('Ignance Paderewski Elementary Learning Academy',),
 ('Inter-American Elementary Magnet School',),
 ('Ira F Aldridge Elementary School',),
 ('Irma C Ruiz Elementary School',),
 ('Irvin C Mollison Elementary School',),
 ("Isabelle C O'Keeffe Elementary School",),
 ('Jackie Robinson Elementary School',),
 ('Jacob Beidler Elementary School',),
 ('James B Farnsworth Elementary School',),
 ('James B McPherson Elementary School',),
 ('James E McDade Elementary Classical School',),
 ('James G Blaine Elementary School',),
 ('James Hedges Elementary School',),
 ('James Madison Elementary School',),
 ('James Monroe Elementary School',),
 ('James N Thorp Elementary School',),
 ('James Otis Elementary School',),
 ('James R Doolittle Jr Elementary School',),
 ('James Russell Lowell Elementary School',),
 ('James Shields Elementary School',),
 ('James Wadsworth Elementary School',),
 ('James Ward Elementary School',),
 ('James Weldon Johnson Elementary School',),
 ('Jane Addams Elementary School',),
 ('Jane A Neil Elementary School',),
 ('Jean Baptiste Beaubien Elementary School',),
 ('Jean D Lafayette Elementary School',),
 ('Jensen Elementary Scholastic Academy',),
 ('Jesse Owens Elementary Community Academy',),
 ('Jesse Sherwood Elementary School',),
 ('Johann W von Goethe Elementary School',),
 ('John A Walsh Elementary School',),
 ('John Barry Elementary School',),
 ('John B Drake Elementary School',),
 ('John B Murphy Elementary School',),
 ('John Calhoun North Elementary School',),
 ('John C Burroughs Elementary School',),
 ('John C Coonley Elementary School',),
 ('John C Dore Elementary School',),
 ('John Charles Haines Elementary School',),
 ('John D Shoop Math-Science Technical Academy Elementary School',),
 ('John F Eberhart Elementary School',),
 ('John Fiske Elementary School',),
 ('John Foster Dulles Elementary School',),
 ('John Greenleaf Whittier Elementary School',),
 ('John Harvard Elementary School of Excellence',),
 ('John Hay Elementary Community Academy',),
 ('John H Hamline Elementary School',),
 ('John H Kinzie Elementary School',),
 ('John H Vanderpoel Elementary Magnet School',),
 ('John J Audubon Elementary School',),
 ('John J Pershing Elementary Humanities Magnet',),
 ('John L Marsh Elementary School',),
 ('John Milton Gregory Elementary School',),
 ('John M Smyth Elementary School',),
 ('Johnnie Colemon Elementary Academy',),
 ('John Palmer Elementary School',),
 ('John P Altgeld Elementary School',),
 ('John Spry Elementary Community School',),
 ('John T McCutcheon Elementary School',),
 ('John T Pirie Fine Arts & Academic Center Elementary School',),
 ('John W Cook Elementary School',),
 ('John W Garvy Elementary School',),
 ('John Whistler Elementary School',),
 ('Jonathan Burr Elementary School',),
 ('Jonathan Y Scammon Elementary School',),
 ('Jordan Elementary Community School',),
 ('Jose De Diego Elementary Community Academy',),
 ('Josefa Ortiz De Dominguez Elementary School',),
 ('Joseph Brennemann Elementary School',),
 ('Joseph E Gary Elementary School',),
 ('Josephine C Locke Elementary School',),
 ('Joseph Jungman Elementary School',),
 ('Joseph Kellman Corporate Community Elementary School',),
 ('Joseph Lovett Elementary School',),
 ('Joseph Stockton Elementary School',),
 ('Joseph Warren Elementary School',),
 ('Joshua D Kershaw Elementary School',),
 ('Josiah Pickard Elementary School',),
 ('Joyce Kilmer Elementary School',),
 ('Julia C Lathrop Elementary School',),
 ('Julia Ward Howe Elementary School of Excellence',),
 ('Kate S Buckingham Special Education Center',),
 ('Kate S Kellogg Elementary School',),
 ('Langston Hughes Elementary School',),
 ('LaSalle Elementary Language Academy',),
 ('LaSalle II Magnet Elementary School',),
 ('Laughlin Falconer Elementary School',),
 ('Laura S Ward Elementary School',),
 ('Lawndale Elementary Community Academy',),
 ('Lazaro Cardenas Elementary School',),
 ('Leif Ericson Elementary Scholastic Academy',),
 ('Lenart Elementary Regional Gifted Center',),
 ('Leslie Lewis Elementary School',),
 ('Lionel Hampton Fine & Performing Arts Elementary School',),
 ('Little Village Elementary School',),
 ('Lorenz Brentano Math & Science Academy Elementary School',),
 ('Louis A Agassiz Elementary School',),
 ('Louisa May Alcott Elementary School',),
 ('Louis Armstrong Math & Science Elementary School',),
 ('Louis Nettelhorst Elementary School',),
 ('Louis Pasteur Elementary School',),
 ('Ludwig Van Beethoven Elementary School',),
 ("Luke O'Toole Elementary School",),
 ('Luther Burbank Elementary School',),
 ('Lyman A Budlong Elementary School',),
 ('Lyman Trumbull Elementary School',),
 ('Mahalia Jackson Elementary School',),
 ('Mancel Talcott Elementary School',),
 ('Manuel Perez Elementary School',),
 ('Marcus Moziah Garvey Elementary School',),
 ('Mariano Azuela Elementary School',),
 ('Maria Saucedo Elementary Scholastic Academy',),
 ('Mark Sheridan Elementary Math & Science Academy',),
 ('Mark Skinner Elementary School',),
 ('Mark Twain Elementary School',),
 ('Marquette Elementary School',),
 ('Martha Ruggles Elementary School',),
 ('Martin A Ryerson Elementary School',),
 ('Marvin Camras Elementary School',),
 ('Mary E Courtenay Elementary Language Arts Center',),
 ('Mary E McDowell Elementary School',),
 ('Mary Gage Peterson Elementary School',),
 ('Mary Lyon Elementary School',),
 ('Mary Mapes Dodge Elementary Renaissance Academy',),
 ('Mary McLeod Bethune Elementary School',),
 ('Matthew A Henson Elementary School',),
 ('Matthew Gallistel Elementary Language Academy',),
 ('Medgar Evers Elementary School',),
 ('Melville W Fuller Elementary School',),
 ('Michael Faraday Elementary School',),
 ('Michael M Byrne Elementary School',),
 ('Mildred I Lavizzo Elementary School',),
 ('Milton Brunson Math & Science Specialty Elementary School',),
 ('Minnie Mars Jamieson Elementary School',),
 ('Morton School of Excellence',),
 ('Moses Montefiore Special Elementary School',),
 ('Mount Greenwood Elementary School',),
 ('Mount Vernon Elementary School',),
 ('Myra Bradwell Communications Arts & Sciences Elementary School',),
 ('Nathanael Greene Elementary School',),
 ('Nathan Hale Elementary School',),
 ('Nathaniel Pope Elementary School',),
 ('Nathan R Goldblatt Elementary School',),
 ('Nathan S Davis Elementary School',),
 ('National Teachers Elementary Academy',),
 ('Near North Elementary School',),
 ('New Field Elementary School',),
 ('Newton Bateman Elementary School',),
 ('Nicholson Technology Academy',),
 ('Ninos Heroes Elementary Academic Center',),
 ('Norman A Bridge Elementary School',),
 ('North River Elementary School',),
 ('Norwood Park Elementary School',),
 ('Ole A Thorp Elementary Scholastic Academy',),
 ('Oliver S Westcott Elementary School',),
 ('Oliver Wendell Holmes Elementary School',),
 ('Oriole Park Elementary School',),
 ('Orozco Fine Arts & Sciences Elementary School',),
 ('Orville T Bright Elementary School',),
 ('Oscar DePriest Elementary School',),
 ('Oscar F Mayer Elementary School',),
 ('Pablo Casals Elementary School',),
 ('Park Manor Elementary School',),
 ('Parkside Elementary Community Academy',),
 ('Patrick Henry Elementary School',),
 ('Paul Cuffe Math-Science Technology Academy Elementary School',),
 ('Paul Revere Elementary School',),
 ('Perkins Bass Elementary School',),
 ('Peter A Reinberg Elementary School',),
 ('Peter Cooper Elementary Dual Language Academy',),
 ('Philip Rogers Elementary School',),
 ('Phillip D Armour Elementary School',),
 ('Phillip Murray Elementary Language Academy',),
 ('Phobe Apperson Hearst Elementary School',),
 ('Pilsen Elementary Community Academy',),
 ('Portage Park Elementary School',),
 ('Pulaski International Academy Elmentary School',),
 ('Rachel Carson Elementary School',),
 ('Ralph H Metcalfe Elementary Community Academy',),
 ('Ravenswood Elementary School',),
 ('Richard Edwards Elementary School',),
 ('Richard Henry Lee Elementary School',),
 ('Richard J Daley Elementary Academy',),
 ('Richard J Oglesby Elementary School',),
 ('Richard Yates Elementary School',),
 ('Robert A Black Magnet Elementary School',),
 ('Robert Emmet Elementary School',),
 ('Robert Fulton Elementary School',),
 ('Robert Healy Elementary School',),
 ('Robert H Lawrence Elementary School',),
 ('Robert L Grimes Elementary School',),
 ('Robert Nathaniel Dett Elementary School',),
 ('Rodolfo Lozano Bilingual & International Center Elementary School',),
 ('Ronald Brown Elementary Community Academy',),
 ('Ronald E McNair Elementary School',),
 ('Rosario Castellanos Elementary School',),
 ('Roswell B Mason Elementary School',),
 ('Rudyard Kipling Elementary School',),
 ('Rueben Salazar Elementary Bilingual Center',),
 ('Rufus M Hitch Elementary School',),
 ('Salmon P Chase Elementary School',),
 ('Samuel Gompers Fine Arts Options Elementary School',),
 ('Sauganash Elementary School',),
 ('Scott Joplin Elementary School',),
 ('Sharon Christa McAuliffe Elementary School',),
 ('Sidney Sawyer Elementary School',),
 ('Simon Guggenheim Elementary School',),
 ('Sir Miles Davis Magnet Elementary Academy',),
 ('Skinner North',),
 ('Socorro Sandoval Elementary School',),
 ('Songhai Elementary Learning Institute',),
 ('South Loop Elementary School',),
 ('South Shore Fine Arts Academy',),
 ('Spencer Technology Academy',),
 ('Stephen Decatur Classical Elementary School',),
 ('Stephen F Gale Elementary Community Academy',),
 ('Stephen K Hayt Elementary School',),
 ('Stone Elementary Scholastic Academy',),
 ('Suder Montessori Magnet Elementary School',),
 ('Talman Elementary School',),
 ('Tarkington School of Excellence Elementary School',),
 ('Telpochcalli Elementary School',),
 ('Theodore Herzl Elementary School',),
 ('Theophilus Schmid Elementary School',),
 ('Thomas A Edison Regional Gifted Center Elementary School',),
 ('Thomas A Hendricks Elementary Community Academy',),
 ('Thomas Chalmers Specialty Elementary School',),
 ('Thomas Drummond Elementary School',),
 ('Thomas Hoyne Elementary School',),
 ('Thomas J Higgins Elementary Community Academy',),
 ('Thomas J Waters Elementary School',),
 ('Turner-Drew Elementary Language Academy',),
 ('Velma F Thomas Early Childhood Center',),
 ('Victor Herbert Elementary School',),
 ('Virgil Grissom Elementary School',),
 ('Walt Disney Magnet Elementary School',),
 ('Walter L Newberry Math & Science Academy Elementary School',),
 ('Walter Q Gresham Elementary School',),
 ('Walter Reed Elementary School',),
 ('Walter S Christopher Elementary School',),
 ('Washington D Smyser Elementary School',),
 ('Washington Irving Elementary School',),
 ('Wendell E Green Elementary School',),
 ('Wendell Smith Elementary School',),
 ('West Park Elementary Academy',),
 ('West Pullman Elementary School',),
 ('West Ridge Elementary School',),
 ('Wildwood Elementary School',),
 ('Willa Cather Elementary School',),
 ('William A Hinton Elementary School',),
 ('William Bishop Owen Scholastic Academy Elementary School',),
 ('William B Ogden Elementary School',),
 ('William C Goudy Elementary School',),
 ('William C Reavis Math & Science Specialty Elementary School',),
 ('William E B Dubois Elementary School',),
 ('William E Dever Elementary School',),
 ('William F Finkl Elementary School',),
 ('William G Hibbard Elementary School',),
 ('William H Brown Elementary School',),
 ('William H King Elementary School',),
 ('William H Prescott Elementary School',),
 ('William H Ray Elementary School',),
 ('William H Ryder Math & Science Specialty Elementary School',),
 ('William H Seward Communication Arts Academy Elementary School',),
 ('William J & Charles H Mayo Elementary School',),
 ('William J Onahan Elementary School',),
 ('William K New Sullivan Elementary School',),
 ('William Penn Elementary School',),
 ('William P Gray Elementary School',),

Double-click __here__ for a hint

<!--
Which column specifies the school type e.g. 'ES', 'MS', 'HS'?
-->

Double-click __here__ for another hint

<!--
Does the column name have mixed case, spaces or other special characters?
If so, ensure you use double quotes around the "Name of the Column"
-->

Double-click __here__ for the solution.

<!-- Solution:

%sql select count(*) from SCHOOLS where "Elementary, Middle, or High School" = 'ES'

Correct answer: 462

-->

### Problem 2

##### What is the highest Safety Score?

In [23]:
%sql select max(SAFETY_SCORE) from SCHOOLS

 * ibm_db_sa://sml38235:***@dashdb-txn-sbox-yp-dal09-14.services.dal.bluemix.net:50000/BLUDB;
Done.

[(99,)]

Double-click __here__ for a hint

<!--
Use the MAX() function
-->

Double-click __here__ for the solution.

<!-- Hint:

%sql select MAX(Safety_Score) AS MAX_SAFETY_SCORE from SCHOOLS

Correct answer: 99
-->

### Problem 3

##### Which schools have highest Safety Score?

In [26]:
%sql SELECT NAME_OF_SCHOOL, SAFETY_SCORE FROM SCHOOLS where Safety_Score=(select MAX(Safety_Score) from SCHOOLS );

 * ibm_db_sa://sml38235:***@dashdb-txn-sbox-yp-dal09-14.services.dal.bluemix.net:50000/BLUDB;
Done.

[('Abraham Lincoln Elementary School', 99),
 ('Alexander Graham Bell Elementary School', 99),
 ('Annie Keller Elementary Gifted Magnet School', 99),
 ('Augustus H Burley Elementary School', 99),
 ('Edgar Allan Poe Elementary Classical School', 99),
 ('Edgebrook Elementary School', 99),
 ('Ellen Mitchell Elementary School', 99),
 ('James E McDade Elementary Classical School', 99),
 ('James G Blaine Elementary School', 99),
 ('LaSalle Elementary Language Academy', 99),
 ('Mary E Courtenay Elementary Language Arts Center', 99),
 ('Northside College Preparatory High School', 99),
 ('Northside Learning Center High School', 99),
 ('Norwood Park Elementary School', 99),
 ('Oriole Park Elementary School', 99),
 ('Sauganash Elementary School', 99),
 ('Stephen Decatur Classical Elementary School', 99),
 ('Talman Elementary School', 99),
 ('Wildwood Elementary School', 99)]

Double-click __here__ for the solution.

<!-- Solution:
In the previous problem we found out that the highest Safety Score is 99, so we can use that as an input in the where clause:

%sql select Name_of_School, Safety_Score from SCHOOLS where Safety_Score = 99

or, a better way:

%sql select Name_of_School, Safety_Score from SCHOOLS where \
  Safety_Score= (select MAX(Safety_Score) from SCHOOLS)


Correct answer: several schools with with Safety Score of 99.
-->

### Problem 4

##### What are the top 10 schools with the highest "Average Student Attendance"?

In [32]:
%sql select NAME_OF_SCHOOL, AVERAGE_STUDENT_ATTENDANCE from SCHOOLS \
order by AVERAGE_STUDENT_ATTENDANCE desc nulls last LIMIT 10

 * ibm_db_sa://sml38235:***@dashdb-txn-sbox-yp-dal09-14.services.dal.bluemix.net:50000/BLUDB;
Done.

[('John Charles Haines Elementary School', '98.40%'),
 ('James Ward Elementary School', '97.80%'),
 ('Edgar Allan Poe Elementary Classical School', '97.60%'),
 ('Orozco Fine Arts & Sciences Elementary School', '97.60%'),
 ('Rachel Carson Elementary School', '97.60%'),
 ('Annie Keller Elementary Gifted Magnet School', '97.50%'),
 ('Andrew Jackson Elementary Language Academy', '97.40%'),
 ('Lenart Elementary Regional Gifted Center', '97.40%'),
 ('Disney II Magnet School', '97.30%'),
 ('John H Vanderpoel Elementary Magnet School', '97.20%')]

Double-click __here__ for the solution.

<!-- Solution:

%sql select Name_of_School, Average_Student_Attendance from SCHOOLS \
    order by Average_Student_Attendance desc nulls last limit 10 

-->

### Problem 5

##### Retrieve the list of 5 Schools with the lowest Average Student Attendance sorted in ascending order based on attendance

In [35]:
#%sql select NAME_OF_SCHOOL, AVERAGE_STUDENT_ATTENDANCE from SCHOOLS \
#order by AVERAGE_STUDENT_ATTENDANCE nulls last LIMIT 5
%sql SELECT Name_of_School, Average_Student_Attendance  \
     from SCHOOLS \
     order by Average_Student_Attendance \
     fetch first 5 rows only

 * ibm_db_sa://sml38235:***@dashdb-txn-sbox-yp-dal09-14.services.dal.bluemix.net:50000/BLUDB;
Done.

[('Richard T Crane Technical Preparatory High School', '57.90%'),
 ('Barbara Vick Early Childhood & Family Center', '60.90%'),
 ('Dyett High School', '62.50%'),
 ('Wendell Phillips Academy High School', '63.00%'),
 ('Orr Academy High School', '66.30%')]

Double-click __here__ for the solution.

<!-- Solution:

%sql SELECT Name_of_School, Average_Student_Attendance  \
     from SCHOOLS \
     order by Average_Student_Attendance \
     fetch first 5 rows only

-->

### Problem 6

##### Now remove the '%' sign from the above result set for Average Student Attendance column

In [37]:
%sql SELECT Name_of_School, REPLACE(Average_Student_Attendance, '%','')  \
     from SCHOOLS \
     order by Average_Student_Attendance \
     fetch first 5 rows only

 * ibm_db_sa://sml38235:***@dashdb-txn-sbox-yp-dal09-14.services.dal.bluemix.net:50000/BLUDB;
Done.

[('Richard T Crane Technical Preparatory High School', '57.90'),
 ('Barbara Vick Early Childhood & Family Center', '60.90'),
 ('Dyett High School', '62.50'),
 ('Wendell Phillips Academy High School', '63.00'),
 ('Orr Academy High School', '66.30')]

Double-click __here__ for a hint

<!--
Use the REPLACE() function to replace '%' with ''
See documentation for this function at:
https://www.ibm.com/support/knowledgecenter/en/SSEPGG_10.5.0/com.ibm.db2.luw.sql.ref.doc/doc/r0000843.html
-->

Double-click __here__ for the solution.

<!-- Hint:

%sql SELECT Name_of_School, REPLACE(Average_Student_Attendance, '%', '') \
     from SCHOOLS \
     order by Average_Student_Attendance \
     fetch first 5 rows only

-->

### Problem 7

##### Which Schools have Average Student Attendance lower than 70%?

In [42]:
%sql SELECT NAME_OF_SCHOOL, Average_Student_Attendance FROM SCHOOLS \
where DECIMAL(REPLACE(Average_Student_Attendance, '%', ''))<70 \
order by Average_Student_Attendance;

 * ibm_db_sa://sml38235:***@dashdb-txn-sbox-yp-dal09-14.services.dal.bluemix.net:50000/BLUDB;
Done.

[('Richard T Crane Technical Preparatory High School', '57.90%'),
 ('Barbara Vick Early Childhood & Family Center', '60.90%'),
 ('Dyett High School', '62.50%'),
 ('Wendell Phillips Academy High School', '63.00%'),
 ('Orr Academy High School', '66.30%'),
 ('Manley Career Academy High School', '66.80%'),
 ('Chicago Vocational Career Academy High School', '68.80%'),
 ('Roberto Clemente Community Academy High School', '69.60%')]

Double-click __here__ for a hint

<!--
The datatype of the "Average_Student_Attendance" column is varchar.
So you cannot use it as is in the where clause for a numeric comparison.
First use the CAST() function to cast it as a DECIMAL or DOUBLE
e.g. CAST("Column_Name" as DOUBLE)
or simply: DECIMAL("Column_Name")
-->

Double-click __here__ for another hint

<!--
Don't forget the '%' age sign needs to be removed before casting
-->

Double-click __here__ for the solution.

<!-- Solution:

%sql SELECT Name_of_School, Average_Student_Attendance  \
     from SCHOOLS \
     where CAST ( REPLACE(Average_Student_Attendance, '%', '') AS DOUBLE ) < 70 \
     order by Average_Student_Attendance
     
or,

%sql SELECT Name_of_School, Average_Student_Attendance  \
     from SCHOOLS \
     where DECIMAL ( REPLACE(Average_Student_Attendance, '%', '') ) < 70 \
     order by Average_Student_Attendance

-->

### Problem 8

##### Get the total College Enrollment for each Community Area

In [51]:
#%sql select COMMUNITY_AREA_NAME, SUM(COLLEGE_ENROLLMENT) from SCHOOLS
%sql select Community_Area_Name, sum(College_Enrollment) AS TOTAL_ENROLLMENT \
   from SCHOOLS \
   group by Community_Area_Name

 * ibm_db_sa://sml38235:***@dashdb-txn-sbox-yp-dal09-14.services.dal.bluemix.net:50000/BLUDB;
Done.

[('ALBANY PARK', 6864),
 ('ARCHER HEIGHTS', 4823),
 ('ARMOUR SQUARE', 1458),
 ('ASHBURN', 6483),
 ('AUBURN GRESHAM', 4175),
 ('AUSTIN', 10933),
 ('AVALON PARK', 1522),
 ('AVONDALE', 3640),
 ('BELMONT CRAGIN', 14386),
 ('BEVERLY', 1636),
 ('BRIDGEPORT', 3167),
 ('BRIGHTON PARK', 9647),
 ('BURNSIDE', 549),
 ('CALUMET HEIGHTS', 1568),
 ('CHATHAM', 5042),
 ('CHICAGO LAWN', 7086),
 ('CLEARING', 2085),
 ('DOUGLAS', 4670),
 ('DUNNING', 4568),
 ('EAST GARFIELD PARK', 5337),
 ('EAST SIDE', 5305),
 ('EDGEWATER', 4600),
 ('EDISON PARK', 910),
 ('ENGLEWOOD', 6832),
 ('FOREST GLEN', 1431),
 ('FULLER PARK', 531),
 ('GAGE PARK', 9915),
 ('GARFIELD RIDGE', 4552),
 ('GRAND BOULEVARD', 2809),
 ('GREATER GRAND CROSSING', 4051),
 ('HEGEWISCH', 963),
 ('HERMOSA', 3975),
 ('HUMBOLDT PARK', 8620),
 ('HYDE PARK', 1930),
 ('IRVING PARK', 7764),
 ('JEFFERSON PARK', 1755),
 ('KENWOOD', 4287),
 ('LAKE VIEW', 7055),
 ('LINCOLN PARK', 5615),
 ('LINCOLN SQUARE', 4132),
 ('LOGAN SQUARE', 7351),
 ('LOOP', 871),
 ('LOWER WEST SIDE', 7257),
 ('MCKINLEY PARK', 1552),
 ('MONTCLARE', 1317),
 ('MORGAN PARK', 3271),
 ('MOUNT GREENWOOD', 2091),
 ('NEAR NORTH SIDE', 3362),
 ('NEAR SOUTH SIDE', 1378),
 ('NEAR WEST SIDE', 7975),
 ('NEW CITY', 7922),
 ('NORTH CENTER', 7541),
 ('NORTH LAWNDALE', 5146),
 ('NORTH PARK', 4210),
 ('NORWOOD PARK', 6469),
 ('OAKLAND', 140),
 ('OHARE', 786),
 ('PORTAGE PARK', 6954),
 ('PULLMAN', 1620),
 ('RIVERDALE', 1547),
 ('ROGERS PARK', 4068),
 ('ROSELAND', 7020),
 ('SOUTH CHICAGO', 4043),
 ('SOUTH DEERING', 1859),
 ('SOUTH LAWNDALE', 14793),
 ('SOUTH SHORE', 4543),
 ('UPTOWN', 4388),
 ('WASHINGTON HEIGHTS', 4006),
 ('WASHINGTON PARK', 2648),
 ('WEST ELSDON', 3700),
 ('WEST ENGLEWOOD', 5946),
 ('WEST GARFIELD PARK', 2622),
 ('WEST LAWN', 4207),
 ('WEST PULLMAN', 3240),
 ('WEST RIDGE', 8197),
 ('WEST TOWN', 9429),
 ('WOODLAWN', 4206)]

Double-click __here__ for a hint

<!--
Verify the exact name of the Enrollment column in the database
Use the SUM() function to add up the Enrollments for each Community Area
-->

Double-click __here__ for another hint

<!--
Don't forget to group by the Community Area
-->

Double-click __here__ for the solution.

<!-- Solution:

%sql select Community_Area_Name, sum(College_Enrollment) AS TOTAL_ENROLLMENT \
   from SCHOOLS \
   group by Community_Area_Name 

-->

### Problem 9

##### Get the 5 Community Areas with the least total College Enrollment  sorted in ascending order

In [53]:
%sql select Community_Area_Name, sum(College_Enrollment) AS TOTAL_ENROLLMENT \
   from SCHOOLS \
   group by Community_Area_Name order by TOTAL_ENROLLMENT fetch first 5 rows only

 * ibm_db_sa://sml38235:***@dashdb-txn-sbox-yp-dal09-14.services.dal.bluemix.net:50000/BLUDB;
Done.

[('OAKLAND', 140),
 ('FULLER PARK', 531),
 ('BURNSIDE', 549),
 ('OHARE', 786),
 ('LOOP', 871)]

Double-click __here__ for a hint

<!--
Order the previous query and limit the number of rows you fetch
-->

Double-click __here__ for the solution.

<!-- Solution:

%sql select Community_Area_Name, sum(College_Enrollment) AS TOTAL_ENROLLMENT \
   from SCHOOLS \
   group by Community_Area_Name \
   order by TOTAL_ENROLLMENT asc \
   fetch first 5 rows only

-->

### Problem 10

##### Get the hardship index for the community area which has College Enrollment of 4638

In [4]:
%%sql 
select hardship_index 
   from chicago_socioeconomic_data CD, schools CPS 
   where CD.ca = CPS.community_area_number 
      and college_enrollment = 4368

 * ibm_db_sa://sml38235:***@dashdb-txn-sbox-yp-dal09-14.services.dal.bluemix.net:50000/BLUDB;
Done.

[(6.0,)]

Double-click __here__ for the solution.

<!-- Solution:
NOTE: For this solution to work the CHICAGO_SOCIOECONOMIC_DATA table 
      as created in the last lab of Week 3 should already exist

%%sql 
select hardship_index 
   from chicago_socioeconomic_data CD, schools CPS 
   where CD.ca = CPS.community_area_number 
      and college_enrollment = 4368

-->

### Problem 11

##### Get the hardship index for the community area which has the highest value for College Enrollment

In [5]:
%sql select ca, community_area_name, hardship_index from chicago_socioeconomic_data \
   where ca in \
   ( select community_area_number from schools order by college_enrollment desc limit 1 )

 * ibm_db_sa://sml38235:***@dashdb-txn-sbox-yp-dal09-14.services.dal.bluemix.net:50000/BLUDB;
Done.

[(5.0, 'North Center', 6.0)]

Double-click __here__ for the solution.

<!-- Solution:
NOTE: For this solution to work the CHICAGO_SOCIOECONOMIC_DATA table 
      as created in the last lab of Week 3 should already exist

%sql select ca, community_area_name, hardship_index from chicago_socioeconomic_data \
   where ca in \
   ( select community_area_number from schools order by college_enrollment desc limit 1 )

-->

## Summary

##### In this lab you learned how to work with a real word dataset using SQL and Python. You learned how to query columns with spaces or special characters in their names and with mixed case names. You also used built in database functions and practiced how to sort, limit, and order result sets, as well as used sub-queries and worked with multiple tables.

Copyright &copy; 2018 [cognitiveclass.ai](cognitiveclass.ai?utm_source=bducopyrightlink&utm_medium=dswb&utm_campaign=bdu). This notebook and its source code are released under the terms of the [MIT License](https://bigdatauniversity.com/mit-license/).